### ISSUE TITLE
OpenEx admin password should be given

### ISSUE THREAD

**Issue by sgros** [boolwinkle/local_openex_setup#2]
There's no information of what username and password for initial access are. This information should be clearly written in the README file.

Also, it would be good that the admin account is admin@openex.local, and not admin@openex.io

**Comment by RavyWavie** [comment]
Initial access credentials are given at the end of the README, under the 'Running' section.

As for the admin email, this is a default value in the OpenEx app itself and cannot be changed through environment variables, instructions on how to change the admin email have been added to the README. We might be able to change this in the future.
